#!/usr/bin/env python3
"""
Emit LaTeX for the HI mass--size (consistency) fit so that the manuscript's
Table~\\ref{table:consistency_fits} AND its inline numbers stay in sync with the
persisted fit (detection-only; upper limits excluded).

Reads:  products/mass_size_consistency_test_summary.json   (no MCMC rerun)
Writes: latex/autogen/macros_mass_size.tex          (scalar macros + sigma-tensions)
        latex/autogen/table_consistency_fits.tex    (the Table-3 body, \\input-ed)

Usage:  python scripts/write_size_mass_macros.py
"""

import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SUMMARY = ROOT / "products" / "mass_size_consistency_test_summary.json"
MACROS_OUT = ROOT / "latex" / "autogen" / "macros_mass_size.tex"
TABLE_OUT = ROOT / "latex" / "autogen" / "table_consistency_fits.tex"

# JSON sample key -> LaTeX macro stem (no digits allowed in macro names)
STEM = {
    "AMIGA": "Amiga",
    "HCGs": "Hcgs",
    "AMIGA + HCGs": "AmigaHcgs",
    "MIGHTEE": "Mightee",
    "Wang2016": "WangSixteen",
    "MIGHTEE + Wang2016": "MighteeWang",
    "Combined sample": "CombinedFit",
}
# Order of rows in Table 3.
TABLE_ORDER = [
    "AMIGA",
    "HCGs",
    "AMIGA + HCGs",
    "MIGHTEE",
    "Wang2016",
    "MIGHTEE + Wang2016",
    "Combined sample",
]
LITERATURE = "MIGHTEE + Wang2016"  # reference for the sigma-tensions


def _suffix(d, suffix):
    for k, v in d.items():
        if k.endswith(suffix):
            return v
    raise KeyError(suffix)


def _param(d, base):
    """Return (median, +err, -err, sigma) for slope/intercept/scatter."""
    med = _suffix(d, "_" + base)
    p16 = _suffix(d, "_" + base + "_p16")
    p84 = _suffix(d, "_" + base + "_p84")
    return med, p84 - med, med - p16, (p84 - p16) / 2.0


def _fmt(med, up, lo, prec=3):
    return f"${med:.{prec}f}^{{+{up:.{prec}f}}}_{{-{lo:.{prec}f}}}$"


def _tension(d, lit, base):
    """|param - param_lit| / sqrt(sigma^2 + sigma_lit^2)."""
    m, _, _, s = _param(d, base)
    ml, _, _, sl = _param(lit, base)
    return abs(m - ml) / math.sqrt(s * s + sl * sl)


def main():
    j = json.load(open(SUMMARY))
    tcf = j["table_consistency_fits"]
    lit = tcf[LITERATURE]

    # ---- scalar macros + sigma-tensions ----
    L = [
        "% Auto-generated by scripts/write_size_mass_macros.py (reads the persisted",
        "% products/mass_size_consistency_test_summary.json; no MCMC rerun).",
        "% Inline mass--size fit numbers, kept in sync with Table:consistency_fits.",
    ]
    for sample, stem in STEM.items():
        d = tcf[sample]
        L.append(rf"\providecommand{{\{stem}Slope}}{{{_suffix(d, '_slope'):.3f}}}")
        L.append(rf"\providecommand{{\{stem}Intercept}}{{{_suffix(d, '_intercept'):.3f}}}")
        L.append(rf"\providecommand{{\{stem}ScatterDex}}{{{_suffix(d, '_scatter'):.3f}}}")
        L.append(rf"\providecommand{{\{stem}N}}{{{int(_suffix(d, '_n'))}}}")
    # sigma-tensions of AMIGA and HCGs vs the literature (MIGHTEE+Wang2016)
    L.append(
        "% sigma-tension = |param - param_lit| / sqrt(sig^2 + sig_lit^2), lit = MIGHTEE+Wang2016"
    )
    for sample, stem in [("AMIGA", "Amiga"), ("HCGs", "Hcgs")]:
        d = tcf[sample]
        L.append(rf"\providecommand{{\{stem}SlopeTension}}{{{_tension(d, lit, 'slope'):.2f}}}")
        L.append(
            rf"\providecommand{{\{stem}InterceptTension}}{{{_tension(d, lit, 'intercept'):.2f}}}"
        )
    MACROS_OUT.write_text("\n".join(L) + "\n")
    print(f"[wrote] {MACROS_OUT}")

    # ---- Table 3 body (wrapped by hi_disk_size_environments.tex with caption + label) ----
    rows = []
    for sample in TABLE_ORDER:
        d = tcf[sample]
        sm, sup, slo, _ = _param(d, "slope")
        im, iup, ilo, _ = _param(d, "intercept")
        cm, cup, clo, _ = _param(d, "scatter")
        rows.append(
            " & ".join(
                [
                    sample,
                    _fmt(sm, sup, slo),
                    _fmt(im, iup, ilo),
                    _fmt(cm, cup, clo),
                    f"{int(_suffix(d, '_n'))}",
                ]
            )
            + r" \\"
        )
    table = [
        "% Auto-generated by scripts/write_size_mass_macros.py. Detection-only fit",
        "% (upper limits excluded). hi_disk_size_environments.tex wraps this with caption+label.",
        r"\begingroup",
        r"\renewcommand{\arraystretch}{1.2}",
        r"\resizebox{\columnwidth}{!}{%",
        r"\begin{tabular}{lcccc}",
        r"\toprule \toprule",
        r"Sample & $m$ & $b$ & $\sigint$ Scatter & $N$ \\",
        r"\midrule",
        ("\n\\addlinespace[0.35em]\n".join(rows)),
        r"\bottomrule",
        r"\end{tabular}%",
        r"}",
        r"\endgroup",
    ]
    TABLE_OUT.write_text("\n".join(table) + "\n")
    print(f"[wrote] {TABLE_OUT}")

    # quick echo of the tension numbers for the prose
    print("  AmigaSlopeTension     =", f"{_tension(tcf['AMIGA'], lit, 'slope'):.2f}")
    print("  AmigaInterceptTension =", f"{_tension(tcf['AMIGA'], lit, 'intercept'):.2f}")
    print("  HcgsSlopeTension      =", f"{_tension(tcf['HCGs'], lit, 'slope'):.2f}")
    print("  HcgsInterceptTension  =", f"{_tension(tcf['HCGs'], lit, 'intercept'):.2f}")
    print(
        "  MighteeScatterDex     =",
        f"{_suffix(tcf['MIGHTEE'], '_scatter'):.3f}",
        "  MighteeN =",
        int(_suffix(tcf["MIGHTEE"], "_n")),
    )


if __name__ == "__main__":
    main()
